Revert "Update to null safety and latest dependencies (#101)"
This reverts commit 347ac5d6de34e30b5b3ddebe36f5c42d33706be7.

$ dart bin/update_homebrew.dart -cdev -r2.15.0-251.0.dev
LateInitializationError: Local 'gitEnvironment' has not been initialized.
dart:_internal                  LateError._throwLocalNotInitialized
bin/update_homebrew.dart 43:9   main.<fn>
===== asynchronous gap ===========================
dart:async                      _asyncThenWrapperHelper
bin/update_homebrew.dart        main.<fn>
package:stack_trace             Chain.capture
bin/update_homebrew.dart 37:15  main